[tool.bumpversion]
current_version = "0.4.4"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)(\\-(?P<release>[a-z]+))?"
serialize = [
    "{major}.{minor}.{patch}-{release}",
    "{major}.{minor}.{patch}"
]
commit = false
tag = false

[tool.bumpversion.parts.release]
optional_value = "beta"
values = [
	"alpha",
	"beta"
]

[[tool.bumpversion.files]]
filename = "compose.yaml"

[[tool.bumpversion.files]]
filename = "pode/__init__.py"

[[tool.bumpversion.files]]
filename = "pyproject.toml"
