[tool.bumpversion]
current_version = "0.4.4-alpha"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)(\\-(?P<release>[a-z]+))?"
serialize = [
    "{major}.{minor}.{patch}-{release}",
    "{major}.{minor}.{patch}"
]
search = "{current_version}"
replace = "{new_version}"
regex = false
ignore_missing_version = false
tag = true
sign_tags = false
tag_name = "v{new_version}"
tag_message = "Bump version: {current_version} → {new_version}"
allow_dirty = false
commit = true
message = "Bump version: {current_version} → {new_version}"
commit_args = ""

[tool.bumpversion.parts.release]
optional_value = "beta"
values = [
	"alpha",
	"beta"
]

[[tool.bumpversion.files]]
filename = "docker-compose.cpython.yml"

[[tool.bumpversion.files]]
filename = "pode/__init__.py"

[[tool.bumpversion.files]]
filename = "pyproject.toml"
