dist: xenial

language: python

matrix:
  include:
    - python: 3.8

install:
  - python -m pip install --upgrade pip setuptools
  - python -m pip install --upgrade codecov
  - python -m pip install --upgrade poetry
  - poetry install

script:
  - pytest
  - python -m doctest README.md

after_success:
  - python -m codecov -f coverage.xml -X gcov
