version: '3'

services:
  pode-cpython:
    build:
      context: .
      args:
        - PYTHON_IMAGE=${CPYTHON_IMAGE_NAME}
        - PYTHON_IMAGE_VERSION=${CPYTHON_IMAGE_VERSION}
        - POETRY_VERSION=${POETRY_VERSION}
    image: lostfan123/pode-cpython:0.3.0-alpha
    volumes:
      - ./pode/:/opt/pode/pode/
      - ./tests/:/opt/pode/tests/
      - ./README.md:/opt/pode/README.md
      - ./pyproject.toml:/opt/pode/pyproject.toml
      - ./pytest.ini:/opt/pode/pytest.ini
    entrypoint: pytest
